version: '3.9'
services:
  app:
    build: ./
    container_name: marine-core-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marine
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    command: java -jar app.jar
  db:
    image: postgres
    container_name: marine-db
    ports:
      - '5431:5432'
    restart: always
    environment:
      POSTGRES_DB: marine
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
