INSERT INTO ship_type (number, value) VALUES ('20', 'WIG');
INSERT INTO ship_type (number, value) VALUES ('21', 'WIG Hazardous category A');
INSERT INTO ship_type (number, value) VALUES ('22', 'WIG Hazardous category B');
INSERT INTO ship_type (number, value) VALUES ('23', 'WIG Hazardous category C');
INSERT INTO ship_type (number, value) VALUES ('24', 'WIG Hazardous category D');
INSERT INTO ship_type (number, value) VALUES ('30', 'Fishing');
INSERT INTO ship_type (number, value) VALUES ('31', 'Towing');
INSERT INTO ship_type (number, value) VALUES ('32', 'Towing: length exceeds 200m or breadth exceeds 25m');
INSERT INTO ship_type (number, value) VALUES ('33', 'Dredging or underwater ops');
INSERT INTO ship_type (number, value) VALUES ('34', 'Diving ops');
INSERT INTO ship_type (number, value) VALUES ('35', 'Military ops');
INSERT INTO ship_type (number, value) VALUES ('36', 'Sailing');
INSERT INTO ship_type (number, value) VALUES ('37', 'Pleasure Craft');
INSERT INTO ship_type (number, value) VALUES ('40', 'HSC');
INSERT INTO ship_type (number, value) VALUES ('41', 'HSC Hazardous category A');
INSERT INTO ship_type (number, value) VALUES ('42', 'HSC Hazardous category B');
INSERT INTO ship_type (number, value) VALUES ('43', 'HSC Hazardous category C');
INSERT INTO ship_type (number, value) VALUES ('44', 'HSC Hazardous category D');
INSERT INTO ship_type (number, value) VALUES ('49', 'HSC No additional information');
INSERT INTO ship_type (number, value) VALUES ('50', 'Pilot Vessel');
INSERT INTO ship_type (number, value) VALUES ('51', 'Search and Rescue vessel');
INSERT INTO ship_type (number, value) VALUES ('52', 'Tug');
INSERT INTO ship_type (number, value) VALUES ('53', 'Port Tender');
INSERT INTO ship_type (number, value) VALUES ('54', 'Anti-pollution equipment');
INSERT INTO ship_type (number, value) VALUES ('55', 'Law Enforcement');
INSERT INTO ship_type (number, value) VALUES ('56', 'Spare - Local Vessel');
INSERT INTO ship_type (number, value) VALUES ('57', 'Spare - Local Vessel');
INSERT INTO ship_type (number, value) VALUES ('58', 'Medical Transport');
INSERT INTO ship_type (number, value) VALUES ('59', 'Noncombatant ship according to RR Resolution No. 18');
INSERT INTO ship_type (number, value) VALUES ('60', 'Passenger');
INSERT INTO ship_type (number, value) VALUES ('61', 'Passenger Hazardous category A');
INSERT INTO ship_type (number, value) VALUES ('62', 'Passenger Hazardous category B');
INSERT INTO ship_type (number, value) VALUES ('63', 'Passenger Hazardous category C');
INSERT INTO ship_type (number, value) VALUES ('64', 'Passenger Hazardous category D');
INSERT INTO ship_type (number, value) VALUES ('65', 'Passenger');
INSERT INTO ship_type (number, value) VALUES ('70', 'Cargo');
INSERT INTO ship_type (number, value) VALUES ('71', 'Cargo Hazardous category A');
INSERT INTO ship_type (number, value) VALUES ('72', 'Cargo Hazardous category B');
INSERT INTO ship_type (number, value) VALUES ('73', 'Cargo Hazardous category C');
INSERT INTO ship_type (number, value) VALUES ('74', 'Cargo Hazardous category D');
INSERT INTO ship_type (number, value) VALUES ('79', 'Cargo No additional information');
INSERT INTO ship_type (number, value) VALUES ('80', 'Tanker');
INSERT INTO ship_type (number, value) VALUES ('81', 'Tanker Hazardous category A');
INSERT INTO ship_type (number, value) VALUES ('82', 'Tanker Hazardous category B');
INSERT INTO ship_type (number, value) VALUES ('83', 'Tanker Hazardous category C');
INSERT INTO ship_type (number, value) VALUES ('84', 'Tanker Hazardous category D');
INSERT INTO ship_type (number, value) VALUES ('89', 'Tanker No additional information');
INSERT INTO ship_type (number, value) VALUES ('90', 'Other Type');
INSERT INTO ship_type (number, value) VALUES ('91', 'Other Type Hazardous category A');
INSERT INTO ship_type (number, value) VALUES ('92', 'Other Type Hazardous category B');
INSERT INTO ship_type (number, value) VALUES ('93', 'Other Type Hazardous category C');
INSERT INTO ship_type (number, value) VALUES ('94', 'Other Type Hazardous category D');
INSERT INTO ship_type (number, value) VALUES ('99', 'Other Type No additional information');


